from abc import ABC, abstractmethod
import logging

logger = logging.getLogger(__name__)

class BaseIngester(ABC):
    """
    Abstract base class for all SimCity data ingesters.
    Enforces a standard event schema and defines the core ingestion loop.
    """
    
    def __init__(self, producer):
        """
        :param producer: An instance of EventProducer to publish events.
        """
        self.producer = producer
        self.is_running = False

    @abstractmethod
    def fetch_latest(self):
        """
        Fetches a batch of the latest events from the source.
        Should yield event dictionaries conforming to the standard schema.
        """
        pass

    def start_stream(self):
        """
        Starts a continuous ingestion loop. Calls fetch_latest() and 
        publishes the yielded events to the producer.
        """
        self.is_running = True
        logger.info(f"Starting stream for {self.__class__.__name__}")
        try:
            for event in self.fetch_latest():
                if not self.is_running:
                    break
                # Validate the event has basic required fields
                if "id" in event and "platform" in event and "timestamp" in event:
                    self.producer.publish(event)
                else:
                    logger.warning(f"Malformed event generated by {self.__class__.__name__}: {event}")
        except Exception as e:
            logger.error(f"Stream failed in {self.__class__.__name__}: {e}")
        finally:
            self.stop_stream()

    def stop_stream(self):
        """ Stops the continuous stream. """
        logger.info(f"Stopping stream for {self.__class__.__name__}")
        self.is_running = False

    @staticmethod
    def format_event(event_id, platform, timestamp, author, content, metadata=None):
        """
        Helper method to format an event matching the expected schema.
        Platform mappings: 0=Reddit, 1=HackerNews, 2=GDELT
        """
        return {
            "id": str(event_id),
            "platform": int(platform),
            "timestamp": float(timestamp),
            "author": str(author),
            "content": str(content),
            "metadata": metadata or {}
        }
